// SPDX-License-Identifier: Apache-2.0
#pragma once

typedef enum {
    EFRP_OK = 0,
    EFRP_WOULD_BLOCK = 1,
    EFRP_EOF = 2,
    EFRP_INVALID_ARGUMENT = -1,
    EFRP_PROTOCOL_ERROR = -2,
    EFRP_CAPACITY_EXCEEDED = -3,
    EFRP_CALLBACK_REJECTED = -4,
    EFRP_TRUNCATED = -5,
    EFRP_INVALID_STATE = -6,
    EFRP_SESSION_CLOSED = -7,
    EFRP_STREAM_RESET = -8,
    EFRP_TIMEOUT = -9,
    EFRP_CRYPTO_ERROR = -10,
    EFRP_AUTHENTICATION_FAILED = -11,
    EFRP_COUNTER_EXHAUSTED = -12,
    EFRP_NEGOTIATION_FAILED = -13,
    EFRP_LOGIN_REJECTED = -14,
    EFRP_TLS_TRUST_ERROR = -15,
    EFRP_TLS_ERROR = -16,
    EFRP_NETWORK_ERROR = -17,
    EFRP_TIME_UNTRUSTED = -18,
    EFRP_CANCELLED = -19,
    EFRP_NO_MEMORY = -20,
    EFRP_DNS_ERROR = -21,
    EFRP_PROXY_REJECTED = -22,
    EFRP_WORK_REJECTED = -23
} efrp_result_t;
